version: '3.8'

services:

  api:
    build: ./backend
    command: gunicorn -c gunicorn.conf.py src.wsgi:application
    env_file:
      - ./backend/.env.dev
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    restart: always
    env_file:
      - ./backend/.env.dev
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    env_file:
      - ./backend/.env.dev
    ports:
      - 5050:80
    volumes:
      - ./pgadmin/pg:/var/lib/pgadmin

volumes:
  postgres_data: