# Generated by Django 3.2.9 on 2022-07-14 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careerguide', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profile'},
        ),
    ]
