# Generated by Django 3.2.9 on 2022-07-15 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerguide', '0002_alter_profile_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='expire',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expire'),
        ),
    ]
