# Generated by Django 3.2.9 on 2022-07-21 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerguide', '0006_alter_questionnaire_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='expire',
            field=models.DateField(blank=True, null=True, verbose_name='Expire'),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(choices=[('art', 'art'), ('science', 'science'), ('commercial', 'commercial'), ('social_science', 'social_science')], max_length=255, verbose_name='Department'),
        ),
    ]
